version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - bank-postgres-data:/var/lib/postgresql/data

volumes:
  bank-postgres-data: